var users = [
{
login: "kehouse",
id: 16854911,
avatar_url: "https://avatars.githubusercontent.com/u/16854911?v=3",
gravatar_id: "",
url: "https://api.github.com/users/kehouse",
html_url: "https://github.com/kehouse",
followers_url: "https://api.github.com/users/kehouse/followers",
following_url: "https://api.github.com/users/kehouse/following{/other_user}",
gists_url: "https://api.github.com/users/kehouse/gists{/gist_id}",
starred_url: "https://api.github.com/users/kehouse/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/kehouse/subscriptions",
organizations_url: "https://api.github.com/users/kehouse/orgs",
repos_url: "https://api.github.com/users/kehouse/repos",
events_url: "https://api.github.com/users/kehouse/events{/privacy}",
received_events_url: "https://api.github.com/users/kehouse/received_events",
type: "User",
site_admin: false,
name: "Kathleen House",
company: null,
blog: null,
location: null,
email: null,
hireable: null,
bio: null,
public_repos: 8,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2016-01-23T17:30:07Z",
updated_at: "2016-02-02T17:34:04Z"
}
]
